name: "Docker Build and Scan"

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Docker image"
        uses: docker/build-push-action@v4
        with:
          tags: dpacgdm/my-secure-app:${{ github.sha }}
          push: false
          load: true

      - name: "Scan image with Trivy"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dpacgdm/my-secure-app:${{ github.sha }}'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
